server:
   port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client-order
  zipkin:
    base-url: http://localhost:9411
logging:
  level:
    root: INFO